{{- $method := .cloneSsh | ternary "git@" "https://" }}
{{- $sep := .cloneSsh | ternary ":" "/" }}
[".config/nvim"]
    type = "git-repo"
    url = "{{- $method -}}github.com{{- $sep -}}hogklint/vim-env.git"
    refreshPeriod = "1h"
    clone.args = ["--branch", "nvim", "--single-branch"]

[".vim"]
    type = "git-repo"
    url = "{{- $method -}}github.com{{- $sep -}}hogklint/vim-env.git"
    refreshPeriod = "1h"
    clone.args = ["--branch", "master", "--single-branch"]

[".zsh"]
    type = "git-repo"
    url = "{{- $method -}}github.com{{- $sep -}}hogklint/zsh-env.git"
    refreshPeriod = "1h"
    clone.args = ["--branch", "master", "--single-branch"]

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "24h"
